# Generated by Django 6.1 on 2026-08-27 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('livre', 'Livre'), ('concours', 'Concours'), ('bac', 'Bac')], max_length=10)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien_telechargement', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BacDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.document')),
                ('annee', models.IntegerField()),
                ('matiere', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConcoursDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.document')),
                ('ecole', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('matiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LivreDetail',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.document')),
                ('auteur', models.CharField(max_length=255)),
            ],
        ),
    ]
