# Generated by Django 6.1 on 2026-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacdetail',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concoursdetail',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livredetail',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
