# Generated by Django 6.1 on 2026-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_telechargement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacdetail',
            name='niveau',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
