# Generated by Django 6.1 on 2026-09-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_bacdetail_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacdetail',
            name='annee',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bacdetail',
            name='delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bacdetail',
            name='matiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bacdetail',
            name='niveau',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bacdetail',
            name='serie',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='concoursdetail',
            name='annee',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='concoursdetail',
            name='delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='concoursdetail',
            name='ecole',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concoursdetail',
            name='matiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='lien_telechargement',
            field=models.CharField(db_index=True, help_text='Google Drive file ID only', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('livre', 'Livre'), ('concours', 'Concours'), ('bac', 'Bac')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='livredetail',
            name='auteur',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livredetail',
            name='delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='telechargement',
            name='date_telechargement',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
